name: Detect Changed Files

on:
  push:
    branches:
      - main

jobs:
  detect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: files
        run: |
          git fetch --depth=5
          
          commit_count=$(git rev-list --count HEAD)
          echo "Total commits: $commit_count"

          if [ "$commit_count" -eq 1 ]; then
            echo "Only one commit found. Returning all files."
            git ls-files > changed.txt
          else
            echo "Showing files changed in last commit:"
            git diff --name-only HEAD~1 HEAD > changed.txt
          fi

          cat changed.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: changed.txt
